after-startup-command = [
  'exec-and-forget /opt/homebrew/bin/sketchybar',
  'exec-and-forget /opt/homebrew/bin/borders active_color=0xffd7f4ff inactive_color=0x00ffffff width=5.0',
  # 'exec-and-forget /opt/homebrew/bin/hs -c "RELOAD_CONFIG()"',
  'exec-and-forget /opt/homebrew/bin/aerospace workspace 3'
]

exec-on-workspace-change = ['/bin/bash', '-c',
  'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
]

start-at-login = true

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 100

default-root-container-layout = 'tiles'

default-root-container-orientation = 'auto'

# on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

automatically-unhide-macos-hidden-apps = false

[key-mapping]
preset = 'qwerty'

[gaps]
inner.horizontal = [{monitor."built-in" = 8}, 15]
inner.vertical =   [{monitor."built-in" = 8}, 15]
outer.left =       [{monitor."built-in" = 8}, 15]
outer.bottom =     [{monitor."built-in" = 8}, 15]
outer.top =        [{monitor."built-in" = 8}, 53]
outer.right =      [{monitor."built-in" = 8}, 15]

[mode.main.binding]

cmd-h = []
cmd-alt-h = []

alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

alt-y = 'workspace 1'
alt-u = 'workspace 2'
alt-i = 'workspace 3'
alt-o = 'workspace 4'
alt-p = 'workspace 5'

alt-shift-y = 'move-node-to-workspace 1'
alt-shift-u = 'move-node-to-workspace 2'
alt-shift-i = 'move-node-to-workspace 3'
alt-shift-o = 'move-node-to-workspace 4'
alt-shift-p = 'move-node-to-workspace 5'

alt-shift-ctrl-y = 'move-node-to-workspace 1 --focus-follows-window'
alt-shift-ctrl-u = 'move-node-to-workspace 2 --focus-follows-window'
alt-shift-ctrl-i = 'move-node-to-workspace 3 --focus-follows-window'
alt-shift-ctrl-o = 'move-node-to-workspace 4 --focus-follows-window'
alt-shift-ctrl-p = 'move-node-to-workspace 5 --focus-follows-window'

alt-f = 'layout floating tiling'
alt-d = 'macos-native-minimize'
alt-z = 'fullscreen'
alt-r = 'flatten-workspace-tree'
alt-enter = 'balance-sizes'

alt-tab = 'workspace-back-and-forth'
alt-leftSquareBracket = 'workspace --wrap-around prev'
alt-rightSquareBracket = 'workspace --wrap-around next'

alt-backtick = 'mode service'

[mode.service.binding]
esc = ['reload-config', 'mode main']
backspace = ['close-all-windows-but-current', 'mode main']

alt-h = ['join-with left', 'mode main']
alt-j = ['join-with down', 'mode main']
alt-k = ['join-with up', 'mode main']
alt-l = ['join-with right', 'mode main']

[workspace-to-monitor-force-assignment]
1 = ['main', 'secondary']
2 = ['secondary', 'main']
3 = ['secondary', 'main']
4 = ['secondary', 'main']
5 = ['secondary', 'main']

[[on-window-detected]]
if.app-id = 'com.tencent.xinWeChat'
if.during-aerospace-startup = true
check-further-callbacks = false
run = ['layout tiling', 'move-node-to-workspace 4']

[[on-window-detected]]
if.app-id = 'com.readdle.SparkDesktop'
if.during-aerospace-startup = true
check-further-callbacks = false
run = ['layout tiling', 'move-node-to-workspace 4']

[[on-window-detected]]
check-further-callbacks = true
if.during-aerospace-startup = false
run = ['layout floating']
